Add explicit compiler and stdlib requirement
conda-forge/xsv-feedstock pull request #3
Opened 2024-06-19 01:31 UTC by peterjc

See https://conda-forge.org/news/2024/01/29/rust-175-osx-sdk/

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2024-06-19 01:31 UTC, peterjc commented
@conda-forge-admin, please rerender

2024-06-19 01:31 UTC, peterjc commented
Let's try adding an explicit compiler requirement - see #3

2024-06-27 02:14 UTC, peterjc commented
TravisCI worked for ARM but failed for ppc64le, specifically ``CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le``, no sign of a log - maybe I left it too long before checking the details?

2024-06-27 03:05 UTC, wolfv commented
I tried to trigger a rerun.

2024-06-28 00:53 UTC, peterjc commented
Sadly I don't think that rerun request worked, still pointing at https://app.travis-ci.com/github/conda-forge/xsv-feedstock/jobs/623091067 which is over a week ago now.

But you're right that this could have been a transient failure worth retrying.

2024-07-01 12:34 UTC, rvalieris commented
I just re-triggered the build now, looks like it passed.

Is this PR replacing the ARM migrator PR ?

2024-07-01 13:31 UTC, wolfv requested changes

2024-07-01 13:31 UTC, wolfv commented on recipe/meta.yaml
>      - rust
you should be able to remove `rust` here when you have it in the build requirements.

2024-07-02 05:23 UTC, peterjc commented
I’m hoping this clerical update will help the macOS ARM update to pass…

2024-07-03 12:30 UTC, rvalieris commented
is this ok to merge then ?

2024-07-03 13:54 UTC, peterjc commented
Yes please

2024-07-03 14:04 UTC, merged